### ISSUE TITLE
How do you get `CA_Stocks_WS.csv`?

### ISSUE THREAD

**Issue by IssamLaradji** [Faidh-Wealth/WS-Trade-Info#1]
Thanks for the code! It is nice to have all the Canadian stocks that can be bought/sold in Wealthsimple listed somewhere.
But I imagine that the stocks `CA_Stocks_WS.csv` get out of date very quickly. 

Could you provide the script you are using to scrape these stock symbols?

**Comment by silvavn** [comment]
The csv is automatically updated weekly. 
I cannot open-source the script unfortunately.
